#!/usr/bin/env bash
# Made by Jesus Palencia
# Licence: GPL-2
LC_ALL=C
key="$HOME/genkey"
listo="$HOME/listo"

rm -f $key
function mensaje (){
	echo "USO: ./securegen nombre apellido su@correo.com clave"
	exit 1
}

if ! [[ -f /usr/bin/gpg ]] || [[ $(dpkg --get-selections | grep -w "gnupg" | awk '{print $1}' | head -1) != gnupg ]]; then
	if [[ "$EUID" != "0" ]]; then
		echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
		exit 1
	fi
	apt-get -q update
	apt-get -qy install gnupg gpgv
	echo "Instalacion finalizada..."
	exit 0
fi

if [[ "$EUID" = "0" ]]; then
	echo -e "\e[00;31mERROR: No debe ser root.\e[00m"
	exit 1
fi

if [[ -z $1 ]]; then
	mensaje	
fi

if [[ -z $2 ]]; then
	mensaje
fi

if [[ -z $3 ]]; then
	mensaje
fi

wget -q -O /tmp/securegnupg - https://raw.githubusercontent.com/sinfallas/securegnupg/master/securegnupg
chmod +x /tmp/securegnupg
source /tmp/securegnupg
rm -f /tmp/securegnupg

echo 'Key-Type: 1' > $key
echo 'Key-Length: 4096' >> $key
echo 'Subkey-Type: 1' >> $key
echo 'Subkey-Length: 4096' >> $key
echo 'Name-Real:' $1 $2 >> $key
echo 'Name-Email:' $3 >> $key
echo 'Expire-Date: 2y' >> $key
echo 'Passphrase:' $4 >> $key
script -q /dev/stdout -c 'gpg --batch --gen-key $key' | tee "$listo"
millave=$(cat "$listo" | grep "gpg: clave" | uniq | awk '{print $3}')
echo "Llave generada $millave"
gpg --keyserver pgp.mit.edu --send-keys $millave
gpg --keyserver pool.sks-keyservers.net --send-keys $millave
gpg --keyserver keyring.debian.org --send-key $millave
gpg --keyserver keyserver.ubuntu.com --send-keys $millave
gpg --keyserver keys.fedoraproject.org --send-keys $millave
gpg --keyserver pgp.uni-mainz.de --send-keys $millave
rm -f $key
rm -f "$listo"
echo "Finalizado..."
exit 0
